# Created with YamlCreate.ps1 v2.1.0 $debug=QUSU.5-1-22567-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: SonicTeamJr.SonicRoboBlast2
PackageVersion: 2.2.11
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/STJr/SRB2/releases/download/SRB2_release_2.2.11/SRB2-v2211-Installer.exe
  InstallerSha256: manifests/s/SonicTeamJr/SonicRoboBlast2/2.2.10
ManifestType: installer
ManifestVersion: 1.1.0
